config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lmdb.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lmdb/urls.py
from . import views
from django.urls import path, include

app_name = "lmdb"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('streaming/', views.streaming_page_view, name='streaming'),
    path('filmes/', views.filmes_page_view, name='filmes'),
    path('contacto/', views.contacto_page_view, name='contacto'),
    path('ajax/validate_username/', views.contacto_page_view),
    path('comentarios/', views.comentarios_page_view, name='comentarios'),
]

lmdb/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
class Contacto(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=60)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Comentario(models.Model):
    clareza = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    rigor = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    precisão = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    profundidade = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    amplitude = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    lógica = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    significância = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    originalidade = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    globalidade = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    comentário = models.CharField(max_length=500, default="Sem comentário")

    def __str__(self):
        return 'Comentário'

class Streaming(models.Model):
    nome = models.CharField(max_length=30)
    link = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30, default='Generalista')
    imagem = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.nome

class Filme(models.Model):
    pass

class Actor(models.Model):
    pass

class Realizador(models.Model):
    pass

lmdb/forms.py
from django import forms
from django.forms import ModelForm, EmailField

from .models import Contacto, Comentario

class NovoContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'

class NovoComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'
        widgets = {'clareza': forms.HiddenInput(),
                   'rigor': forms.HiddenInput(),
                   'precisão': forms.HiddenInput(),
                   'profundidade': forms.HiddenInput(),
                   'amplitude': forms.HiddenInput(),
                   'lógica': forms.HiddenInput(),
                   'significância': forms.HiddenInput(),
                   'originalidade': forms.HiddenInput(),
                   'globalidade': forms.HiddenInput(),
                   'comentário': forms.HiddenInput()}

lmdb/views.py
import json

from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .forms import NovoContactoForm, NovoComentarioForm
from .models import Contacto, Comentario, Streaming

def home_page_view(request):
	return render(request, 'lmdb/home.html')

def streaming_page_view(request):
	context = {'streaming_plat': Streaming.objects.all()}
	print(Streaming.objects.all())
	return render(request, 'lmdb/streaming.html', context)

def filmes_page_view(request):
	return render(request, 'lmdb/filmes.html')

def contacto_page_view(request):
	form = NovoContactoForm(request.POST or None)
	if 'edita_contacto_id' in request.POST.keys():
		editar_id = request.POST.get('edita_contacto_id')
		contacto_a_editar = Contacto.objects.get(pk=editar_id)
		json_data = serializers.serialize("json", [contacto_a_editar])
		return HttpResponse(json_data, content_type="application/json")
	if 'edita_contacto_flag' in request.POST.keys():
		editar_id = request.POST.get('edita_contacto_id1')
		Contacto.objects.filter(pk=editar_id).update(first_name = request.POST.get('first_name'))
		Contacto.objects.filter(pk=editar_id).update(last_name = request.POST.get('last_name'))
		Contacto.objects.filter(pk=editar_id).update(email = request.POST.get('email'))
		return HttpResponseRedirect(reverse('lmdb:contacto'))
	if 'contacto_id' in request.POST.keys():
		contacto_eliminar = request.POST.get('contacto_id')
		Contacto.objects.get(pk=contacto_eliminar).delete()
		return HttpResponseRedirect(reverse('lmdb:contacto'))
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('lmdb:contacto'))

	context = {'contactos': Contacto.objects.all(), 'form': form}
	return render(request, 'lmdb/contacto.html', context)

def comentarios_page_view(request):
	form = NovoComentarioForm(request.POST or None)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('lmdb:comentarios'))

	context = {'form': form}
	return render(request, 'lmdb/comentarios.html', context)

lmdb/templates/lmdb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}{% include 'lmdb/head.html' %}{% endblock head%}
</head>
<body>
    <nav>
        {% block navbar %}{% include 'lmdb/navbar.html' %}{% endblock navbar%}
    </nav>
    <main class="ui main container">
        {% block main %}
        {% endblock %}
    </main>
</body>
</html>

lmdb/templates/lmdb/comentarios.html
{% extends 'lmdb/base.html' %}
{% load static %}
{% block main %}
    <h2 class="ui center aligned icon header">
        <i class="comment outline icon"></i>
        A sua opinião
    </h2>

    <div class="ui grid">
        <div class="eight wide centered column">
            <div class="ui raised card">
                <div class="image">
                    <img src="https://h5p.org/sites/default/files/styles/medium-logo/public/logos/chart-icon-color.png?itok=kpLTYHHJ">
                </div>
                <div class="content">
                    <div class="header">Gráfico</div>
                </div>
            </div>
        </div>
        <div class="eight wide centered column">
            <div class="ui center aligned container">
                <p>
                    A sua opinião é importante para nós.
                </p>
                <button class="ui primary button" type="button" id="novo_comentario_button">Novo</button>
            </div>
        </div>
    </div>

    {% block modal_novo_comentario %}{% include 'lmdb/modals/modal_novo_comentario.html' %}{% endblock modal_novo_comentario%}

    <script src="{% static 'js/comentarios.js' %}"></script>
{% endblock %}

lmdb/templates/lmdb/contacto.html
{% extends 'lmdb/base.html' %}
{% load static %}
{% block main %}

    <h2 class="ui center aligned icon header">
        <i class="circular address book outline icon"></i>
        Contactos
    </h2>

    <table class="ui stripped table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th class="right aligned">Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for contacto in contactos %}
                <tr>
                    <td>{{ contacto.first_name }}  {{ contacto.last_name }}</td>
                    <td>{{ contacto.email }}</td>
                    <td class="right aligned">
                        <span><i class="edit outline icon editicon" id="{{ contacto.id }}"></i></span>
                        <span><i class="trash alternate outline icon deleteicon" id="{{ contacto.id }}"></i></span>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <button class="ui primary button" id="novo_contacto_button">
        Adicionar contacto
    </button>

    {% block modal_novo_contacto %}{% include 'lmdb/modals/modal_novo_contacto.html' %}{% endblock modal_novo_contacto%}
    {% block modal_edita_contacto %}{% include 'lmdb/modals/modal_edita_contacto.html' %}{% endblock modal_edita_contacto%}
    {% block modal_apaga_contacto %}{% include 'lmdb/modals/modal_apaga_contacto.html' %}{% endblock modal_apaga_contacto%}

    <script src="{% static 'js/contacto.js' %}"></script>

{% endblock %}

lmdb/templates/lmdb/filmes.html
{% extends 'lmdb/base.html' %}
{% load static %}
{% block main %}
    <h2 class="ui center aligned icon header">
        <i class="circular search icon"></i>
        Pesquisa de filmes
    </h2>
    <script src="{% static 'js/filmes.js' %}"></script>
{% endblock %}

lmdb/templates/lmdb/head.html
<meta charset="UTF-8">
<title>LMDB</title>
{% load static %}
<link rel="stylesheet" href='{% static 'css/base.css' %}'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

lmdb/templates/lmdb/home.html
{% extends 'lmdb/base.html' %}
{% load static %}
{% block main %}
    <h2 class="ui center aligned icon header">
        <i class="circular tv icon"></i>
        Lançamentos da semana
    </h2>

    <div class="ui four raised cards">
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/dreamhorse.jpg' %}">
            </div>
            <div class="content">
                <a class="header">Dream horse</a>
                <div class="meta">
                    <span class="date">Junho de 2021</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    22 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/thedry.jpg' %}">
            </div>
            <div class="content">
                <a class="header">The dry</a>
                <div class="meta">
                    <span class="date">Janeiro de 2021</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    51 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/finalaccount.jpg' %}">
            </div>
            <div class="content">
                <a class="header">Final account</a>
                <div class="meta">
                    <span class="date">Maio de 2021</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    31 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/americanfighter.jpg' %}">
            </div>
            <div class="content">
                <a class="header">American fighter</a>
                <div class="meta">
                    <span class="date">Dezembro de 1988</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    321 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/springblossom.jpg' %}">
            </div>
            <div class="content">
                <a class="header">Spring blossom</a>
                <div class="meta">
                    <span class="date">Maio de 2021</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    76 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/hitler.jpg' %}">
            </div>
            <div class="content">
                <a class="header">When Hitler stole pink rabbit</a>
                <div class="meta">
                    <span class="date">Dezembro de 2019</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    5 Likes
                </a>
            </div>
        </div>
        <div class="ui card">
            <div class="image test">
                <img src="{% static 'images/seance.jpg' %}">
            </div>
            <div class="content">
                <a class="header">Seance</a>
                <div class="meta">
                    <span class="date">Novembro de 2021</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                    <i class="thumbs up outline icon"></i>
                    68 Likes
                </a>
            </div>
        </div>
    </div>

    <script src="{% static 'js/home.js' %}"></script>

{% endblock %}

lmdb/templates/lmdb/modals/modal_apaga_contacto.html
<div class="ui mini modal" id="modal_confirma_delete">
    <i class="close icon"></i>
    <div class="content">
        <form class="ui form" method="POST">
            {% csrf_token %}
            <div class="field">
                <h3 class="ui header">
                    <i class="trash alternate outline icon"></i>
                    <div class="content">
                        Pretende apagar o contacto?
                    </div>
                </h3>
            </div>
            <div class="field">
                <input type="hidden" name="contacto_id" id="contacto_id">
            </div>
            <button class="ui negative button" type="submit">Eliminar</button>
            <button class="ui button" type="button" id="remove_contacto_fecha_modal">Cancelar</button>
        </form>
    </div>
</div>

lmdb/templates/lmdb/modals/modal_edita_contacto.html
<div class="ui modal" id="modal_edita_contacto">
    <i class="close icon"></i>
    <div class="header">Novo contacto</div>
    <div class="content">
        <form class="ui form" method="POST">
            {% csrf_token %}
            <div class="two fields">
                <div class="field">
                    <label>Primeiro nome</label>
                    <input type="text" name="first_name" id="first_name_edit">
                </div>
                <div class="field">
                    <label>Apelido</label>
                    <input type="text" name="last_name" id="flast_name_edit">
                </div>
            </div>
            <div class="field">
                <label>Email</label>
                <input type="email" name="email" id="email_edit">
            </div>
            <input type="hidden" name="edita_contacto_flag" id="edita_contacto_flag">
            <input type="hidden" name="edita_contacto_id1" id="edita_contacto_id1">
            <button class="ui primary button" type="submit">Alterar contacto</button>
            <button class="ui button" type="reset" id="edita_contacto_fecha_modal">Cancelar</button>
        </form>
    </div>
</div>

lmdb/templates/lmdb/modals/modal_novo_comentario.html
<div class="ui large modal" id="modal_novo_comentario">
    <i class="close icon"></i>
    <div class="content">
        <form class="ui form" method="POST" id="comentario_form">
            {% csrf_token %}
            <div class="two fields">
                <div class="field">
                    <div class="field">
                        <div class="two fields">
                            <div class="field">
                                <label>Clareza</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_clareza"></div>
                                {{ form.clareza }}
                            </div>
                            <div class="field">
                                <label>Rigor</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_rigor"></div>
                                {{ form.rigor }}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="two fields">
                            <div class="field">
                                <label>Precisão</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_precisao"></div>
                                {{ form.precisão }}
                            </div>
                            <div class="field">
                                <label>Profundidade</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_profundidade"></div>
                                {{ form.profundidade }}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="two fields">
                            <div class="field">
                                <label>Amplitude</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_amplitude"></div>
                                {{ form.amplitude }}
                            </div>
                            <div class="field">
                                <label>Lógica</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_logica"></div>
                                {{ form.lógica }}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <div class="two fields">
                            <div class="field">
                                <label>Significância</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_significancia"></div>
                                {{ form.significância }}
                            </div>
                            <div class="field">
                                <label>Originalidade</label>
                                <div class="ui star rating" data-rating="5" data-max-rating="10" id="rating_originalidade"></div>
                                {{ form.originalidade }}
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label>Globalidade</label>
                        <div class="ui heart rating" data-rating="8" data-max-rating="10" id="rating_global"></div>
                        {{ form.globalidade }}
                    </div>
                </div>
                <div class="field">
                    <label>Comentário</label>
                    <textarea maxlength="500" id="comentario_input"></textarea>
                    {{ form.comentário }}
                </div>
            </div>
            <button class="ui primary button" type="button" id="comentario_submit">Submeter</button>
            <button class="ui button" type="reset" id="novo_comentario_fecha_modal">Cancelar</button>
        </form>
    </div>
</div>

lmdb/templates/lmdb/modals/modal_novo_contacto.html
<div class="ui modal" id="modal_novo_contacto">
    <i class="close icon"></i>
    <div class="header">Novo contacto</div>
    <div class="content">
        <form class="ui form" method="POST">
            {% csrf_token %}
            <div class="two fields">
                <div class="field">
                    <label>Primeiro nome</label>
                    {{ form.first_name }}
                </div>
                <div class="field">
                    <label>Apelido</label>
                    {{ form.last_name }}
                </div>
            </div>
            <div class="field">
                <label>Email</label>
                {{ form.email }}
            </div>
            <button class="ui primary button" type="submit">Criar contacto</button>
            <button class="ui button" type="reset" id="novo_contacto_fecha_modal">Cancelar</button>
        </form>
    </div>
</div>

lmdb/templates/lmdb/navbar.html
<div class="ui blue inverted borderless menu fixed top">
    <div class="ui container">
        <a class="item" href="{% url 'lmdb:home' %}" id="home_page">
            Home
        </a>
        <a class="item" href="{% url 'lmdb:filmes' %}" id="filmes_page">
            Filmes
        </a>
        <a class="item" href="{% url 'lmdb:streaming' %}" id="streaming_page">
            Streaming
        </a>
        <a class="item" href="{% url 'lmdb:contacto' %}" id="contacto_page">
            Contacto
        </a>
        <a class="item" href="{% url 'lmdb:comentarios' %}" id="comentarios_page">
            Comentários
        </a>
        <div class="right menu">
            <div class="item">
                <div class="ui primary button">Login</div>
            </div>
        </div>
    </div>
</div>

lmdb/templates/lmdb/streaming.html
{% extends 'lmdb/base.html' %}
{% load static %}
{% block main %}
    <h2 class="ui center aligned icon header">
        <i class="circular video icon"></i>
        Plataformas de streaming
    </h2>

    <div class="ui four raised cards">
        {% for streaming in streaming_plat %}
            <div class="ui card">
            <div class="image">
                <img src="{{ streaming.imagem.url }}">
            </div>
            <div class="content">
                <a class="header" href="{{ streaming.link }}" target="_blank">{{ streaming.nome }}</a>
                <div class="description">
                    {{ streaming.tipo }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <script src="{% static 'js/streaming.js' %}"></script>

{% endblock %}